//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>AirportInformation</summary>
	[PublishedContentModel("airportInformation")]
	public partial class AirportInformation : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "airportInformation";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AirportInformation(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AirportInformation, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Detail Information
		///</summary>
		[ImplementPropertyType("detailInformation")]
		public string DetailInformation
		{
			get { return this.GetPropertyValue<string>("detailInformation"); }
		}

		///<summary>
		/// ICAO Code
		///</summary>
		[ImplementPropertyType("iCAOCode")]
		public string ICaocode
		{
			get { return this.GetPropertyValue<string>("iCAOCode"); }
		}

		///<summary>
		/// Wikifolio Boxes
		///</summary>
		[ImplementPropertyType("wikifolioBoxes")]
		public Newtonsoft.Json.Linq.JToken WikifolioBoxes
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("wikifolioBoxes"); }
		}
	}
}
